apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kredi-ingress
  namespace: production  
  annotations:
    kubernetes.io/ingress.class: "nginx" 
spec:
  rules:
    - host: kredi.quandoo.click
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.servicename}}
                port:
                  number: 80  
