apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spring-deployment-spc
  namespace: {{ .Values.namespace }}
spec:
  provider: aws
  secretObjects:
  - secretName: k8s-secret
    type: Opaque
    data:
    - objectName: db_username
      key: DATABASE_USER_NAME
    - objectName: db_password
      key: DATABASE_USER_PASSWORD
  parameters:
    objects: |
        - objectName: "db_credentials_new"
          objectType: "secretsmanager"
    region: "us-east-1"