apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spring-deployment-spc
  namespace: {{ .Values.namespace }}
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "db_credentials"
          objectType: "secretsmanager"
    region: "us-east-1"