apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-manager-sa
  namespace: {{ .Values.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::886243529181:role/kredi-prod-rds-secret-role
    