# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: project cicd flow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
        
    - name: Build with Maven
      run: mvn clean package

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v2
      with: 
        context: .
        push: true
        tags: lekelee/user-microservice:${{ github.run_number }}

    # - name: Install Terraform
    #   uses: hashicorp/setup-terraform@v3
    #   with:
    #     terraform_version: 1.5.7
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Initialize Terraform workspace
      run: cd terraform && terraform init -reconfigure
      
    - name: Plan Terraform configuration
      run: cd terraform && terraform plan

    - name: Apply Terraform configuration
      run: cd terraform && terraform apply -auto-approve

    - name: Update kube config
      run: aws eks update-kubeconfig --name kredi-cluster --region us-east-1

    - uses: azure/setup-helm@v4.2.0
      with:
         version: '3.14.3' 
      id: install
      
    # - name: Add Helm repository for secrets-store-csi-driver
    #   run: helm repo add secrets-store-csi-driver https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
      
    - name: Deploy csi secret store using Helm
      run: helm upgrade --install  csi-secrets-store kubernetes/secrets-store-csi-driver --set syncSecret.enabled=true --namespace kube-system

    - name: Deploy aws-provider-installer using Helm
      run: helm upgrade --install aws-provider-installer kubernetes/aws-provider-installer 

    - name: Deploy nginx-ingress-controller using Helm
      run: helm upgrade --install nginx-controller kubernetes/nginx-ingress-controller

    - name: Deploy Kredi application using Helm
      run: helm upgrade --install kredi-app kubernetes/kredi-app --set image.name=lekelee/user-microservice --set image.tag=${{ github.run_number }}

    - name: Upload Helm Charts to S3
      run: |
        aws s3 cp --recursive kubernetes s3://kredi-remote-backend/helm-charts/
    # - name: Destroy Infrastructure  Using Terraform 
    #   run: cd terraform && terraform destroy -auto-approve
